# SPDX-License-Identifier: Apache-2.0

# This file runs all lint-like tests that should be validated in CI prior to
# building the top-level Containerfile.  It is generally built via the
# containerized-build.sh script, and doesn't need to be tagged or uploaded.

FROM quay.io/projectquay/golang:1.22

# Needed for golangci-lint
RUN dnf install -qy diffutils && dnf clean all

WORKDIR /kubesan

# Although "make" will also build these tools, pre-building them as a
# separate RUN now lets us cache things for faster container reuse
COPY go.mod go.sum Makefile .golangci.yml PROJECT ./
RUN make controller-gen golangci-lint

# Copy the files to be linted. This skips vendor/ on purpose.
COPY api/ api/
COPY cmd/ cmd/
COPY deploy/ deploy/
COPY hack/ hack/
COPY internal/ internal/

RUN make generate

RUN make vet lint
