# SPDX-License-Identifier: Apache-2.0

# This kustomization lets you install a namespace for use with KubeSAN.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
