# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-controller-manager
  namespace: kubesan-system
spec:
  replicas: 2
  selector:
    matchLabels: &labels
      app.kubernetes.io/component: cluster-controller-manager
  template:
    metadata:
      labels: *labels
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: cluster-controller-manager
      terminationGracePeriodSeconds: 10
      hostPID: true
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          whenUnsatisfiable: DoNotSchedule
          topologyKey: kubernetes.io/hostname
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels: *labels
          matchLabelKeys:
            - pod-template-hash
      containers:
        - name: manager
          image: kubesan
          args:
            - cluster-controller-manager
            - --leader-elect
          env:
            - name: KUBESAN_GROUP
              value: kubesan.gitlab.io
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            privileged: true
