# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-controller-manager
  namespace: kubesan-system
spec:
  selector:
    matchLabels: &labels
      kubesan.gitlab.io/component: node-controller-manager
  template:
    metadata:
      labels: *labels
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: node-controller-manager
      terminationGracePeriodSeconds: 10
      hostPID: true
      containers:
        - name: manager
          image: quay.io/kubesan/kubesan:v0.5.2
          args:
            - node-controller-manager
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          # TODO(user): Configure the resources accordingly based on the project requirements.
          # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            privileged: true
