# SPDX-License-Identifier: Apache-2.0

# This kustomization installs KubeSAN in a bare-bones cluster.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: kubesan
    newName: quay.io/kubesan/kubesan
    # To cut a release, bump the version string in
    # internal/common/config/config.go, then copy it here in place of 'latest'.
    newTag: v0.10.2

labels:
  - pairs:
      app.kubernetes.io/name: kubesan
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/version: v0.10.2
    includeTemplates: true

resources:
  - ../namespace
  - crd
  - csi
  - manager
  - rbac
