# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: kubesan
    newName: quay.io/kubesan/kubesan
    # To cut a release, bump the version string in
    # internal/common/config/config.go, then copy it here in place of 'latest'.
    newTag: v0.9.0

commonLabels:
  app.kubernetes.io/name: kubesan
  app.kubernetes.io/version: v0.9.0

resources:
  - crd
  - csi
  - manager
  - namespace.yaml
  - rbac

# TODO: Remove this patch once snapshots are supported
# Disable the csi-snapshotter sidecar as long as it has nothing to do
patches:
  - target:
      kind: Deployment
      name: csi-controller-plugin
    patch: |-
      - op: test
        path: /spec/template/spec/containers/2/name
        value: csi-snapshotter
      - op: remove
        path: /spec/template/spec/containers/2
