# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: kubesan
    newName: quay.io/kubesan/kubesan
    # To cut a release, bump the version string in
    # internal/common/config/config.go, then copy it here in place of 'latest'.
    newTag: latest

commonLabels:
  app.kubernetes.io/name: kubesan
  app.kubernetes.io/version: latest

resources:
  - crd
  - csi
  - manager
  - namespace.yaml
  - rbac
